name: "Install Dependencies"
description: "Python dependencies"

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v3
    with:
      repository: christophfroehlich/control.ros.org
      ref: reusable_wf
      fetch-depth: 0
  - uses: actions/setup-python@v4
    with:
      python-version: '3.8'
      cache: 'pip'
  - name: Install Python dependencies
    run: |
      python -m pip install --upgrade pip
      pip install --upgrade --requirement requirements.txt
    shell: bash
  - name: Install generate_parameter_library
    run: |
      cd
      git clone https://github.com/PickNikRobotics/generate_parameter_library.git
      cd generate_parameter_library/generate_parameter_library_py/
      python -m pip install .
    shell: bash
