#!/usr/bin/env bash

# shellckeck source=deploy_defines
source deploy_defines

create_deployment_branches () {
    # checkout a base from which deply branches are derived
    git checkout "$base_branch" || { echo "Exiting!"; exit "$ERRCODE"; }

    # create temporary branches, clone subdirectories 
    for branch in "${!branch_version[@]}";
        do echo "Create temporary changes for branch: $branch.  - With version:${branch_version[$branch]}";
        git checkout -b "$branch"
        # change .gitignore, needed to include submodules. sed matches doc/ros2_control*, so all submodules are excluded
        sed -i "s/doc\/ros2_control/\#doc\/ros2_control/g" .gitignore
        # make sure all submodules are inited
        echo "Clone repositories for $branch and checkout ${branch_version[$branch]}"
        for submodule in "${submodules[@]}";
            do echo "Create doc/$submodule";
                git clone https://github.com/ros-controls/"$submodule" -b "${branch_version[$branch]}" doc/"$submodule"
                cd doc/"$submodule" || { echo "Could not clone $submodule to doc/ directory. Exiting!"; exit "$ERRCODE"; } 
                rm -rf .git/
                cd ../../ 
        done
        git add .
        git commit -m "Add temporary changes for multi version"
        git checkout "$base_branch"
        rm -rf doc/"$submodule"
    done
}

create_deployment_branches