#!/usr/bin/env bash

# shellckeck source=deploy_defines
source deploy_defines

# checkout a base from which deply branches are derived
git checkout "$base_branch" || { echo "Exiting!"; exit $ERRCODE; }

# create temporary branches, clone subdirectories 
for branch in "${!branch_version[@]}";
    do echo "Revert to last changes before temporary multiversion commit on: $branch.";
    git checkout "$branch"
    git reset --hard HEAD~1
    git checkout "$base_branch"
done