#!/usr/bin/env bash

# temporary branches which are used for deployment and corresponding branch which should be checked out in the submodule
declare -A branch_version=( ["foxy_deploy"]="foxy" ["galactic_deploy"]="galactic" ["rolling_deploy"]="rolling")
submodules=("ros2_control" "ros2_controllers" "ros2_control_demos")
base_branch="add_multi_version_temp_branch"