#!/usr/bin/env bash

# shellckeck source=deploy_defines
# source deploy_defines regardless of startingpoint
DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/deploy_defines" || { echo "Could not source deploy_defines script. This is needed for correct execution. Exiting!"; exit; }

add_sub_repositories () {
    # checkout a base for defined starting point
    cd "$base_dir" || { echo "Could not checkout base dir of control.ros.org. Exiting!"; exit "$ERRCODE"; }
    for repo_name in "${!subrepo_url[@]}";
        do echo "Create doc/$repo_name";
        git clone "${subrepo_url[$repo_name]}" -b "$api_branch" doc/"$repo_name"
    done
}

add_sub_repositories
