#!/usr/bin/env bash

# shellckeck source=deploy_defines
# source deploy_defines regardless of startingpoint
DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/deploy_defines" || { echo "Could not source deploy_defines script. This is needed for correct execution. Exiting!"; exit; }

add_sub_repositories () {
    # checkout a base for defined starting point
    cd "$base_dir" || { echo "Could not checkout base dir of control.ros.org. Exiting!"; exit "$ERRCODE"; }
    for repo_name in "${!subrepo_url[@]}"; do
        if [ ! -d "doc/$repo_name" ]; then
          echo "Create doc/$repo_name and checkout $base_branch branch"
          git clone "${subrepo_url[$repo_name]}" -b "$base_branch" doc/"$repo_name"
        else
          echo "Update doc/$repo_name and checkout $base_branch branch"
          cd doc/"$repo_name"
          git fetch origin
          git checkout "$base_branch"
          git pull
          cd "$base_dir"
        fi
        if [ ! -z ${subrepo_pr[$repo_name]} ]; then
          echo "checkout PR: ${subrepo_pr[$repo_name]}"
          cd doc/"$repo_name"
          git fetch origin ${subrepo_pr[$repo_name]}:PR
          git checkout PR
          cd "$base_dir"
        fi
    done
}

add_sub_repositories
add_pr_stats_file
