#!/usr/bin/env bash
# This script is used to check the links in the ROS documentation.
# due to a bug in the sphinx linkchecker, github anchors are false positives and
# have to be explicitly ignored
# https://github.com/sphinx-doc/sphinx/issues/9016

LOGFILE="linkcheck.log"
cleanup () {
  rm "$LOGFILE"
	rm -rf doc/api/
}

cp -r $1/html/doc/api/. doc/api/
make linkcheck > "$LOGFILE"
if grep broken "$LOGFILE" | grep -v -E 'github.*Anchor'; then
    num_broken=$(grep broken "$LOGFILE" | grep -v -E 'github.*Anchor' | wc -l)
    echo "Broken links found: $num_broken"
    cleanup
    exit 1
fi
cleanup
exit 0
