#!/usr/bin/env bash
# This script is used to check the links in the ROS documentation.
# due to a bug in the sphinx linkchecker, github anchors are false positives and
# have to be explicitly ignored
# https://github.com/sphinx-doc/sphinx/issues/9016
make linkcheck > linkcheck.log
if grep broken linkcheck.log | grep -v -E 'github.*Anchor'; then
    num_broken=$(grep broken linkcheck.log | grep -v -E 'github.*Anchor' | wc -l)
    echo "Broken links found: $num_broken"
    rm linkcheck.log
    exit 1
fi
rm linkcheck.log
exit 0
