#!/usr/bin/env bash

# shellckeck source=deploy_defines
# source deploy_defines regardless of startingpoint
DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/deploy_defines" || { echo "Could not source deploy_defines script. This is needed for correct execution. Exiting!"; exit; }

create_api () {
    cd doc/
    doxygen Doxyfile
    mkdir -p "$base_dir"/"$build_dir"/html/doc/api/
    cp -r tmp/html/. "$base_dir"/"$build_dir"/html/doc/api/
    rm -rf tmp
}

cd "$base_dir" || { echo "Could not checkout base dir of control.ros.org. Exiting!"; exit "$ERRCODE"; }
create_api
