#!/usr/bin/env bash

# This file includes all the definitions used in the other scripts
api_repo="ros2_control"
api_dir="doc/$api_repo"
script_base_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# should by control.ros.org folder
base_dir="$(dirname "$script_base_dir")"
# branch from which is started to checkout other branches
base_branch="master"
build_dir="_build"

# reviewer stats
reviewer_stats_files=("maintainers_stats_recent.html"
  "reviewers_stats_recent.html"
  "maintainers_stats.html"
  "reviewers_stats.html")
reviewer_stats_cache_folder="reviews"
reviewer_stats_target_folder="./doc/acknowledgements"

add_reviewer_stats_file () {
  for reviewer_stats_filename in "${reviewer_stats_files[@]}"; do
    ORIGFILE="$HOME/$reviewer_stats_cache_folder/$reviewer_stats_filename"
    # echo $ORIGFILE
    if test -f "$ORIGFILE"; then
      echo "Copy reviewer stats file '${reviewer_stats_filename}' to '${reviewer_stats_target_folder}'"
      cp ${ORIGFILE} ${reviewer_stats_target_folder}
    else
      echo "Create empty reviewer stats file '${reviewer_stats_filename}' in '${reviewer_stats_target_folder}'"
      touch ${reviewer_stats_target_folder}/${reviewer_stats_filename}
    fi
  done
}

# definition single html
# the branch from which the api is checked out and built
api_branch="master"

# definitions for multiversion
# branches on which the temporary commits are created and which branch should be checked out in the subrepositories
# ["branch checked out for multiversion"]="branch checked out for all subrepos"
declare -A branch_version=( ["foxy"]="foxy" ["galactic"]="galactic" ["humble"]="humble" ["iron"]="master" ["master"]="master") # master is rolling

# the subrepos which are cloned into the branches and, optionally, their corresponding PR for checkout
declare -A subrepo_url=( ["ros2_control"]="https://github.com/ros-controls/ros2_control" ["ros2_controllers"]="https://github.com/ros-controls/ros2_controllers" ["ros2_control_demos"]="https://github.com/ros-controls/ros2_control_demos" ["gazebo_ros2_control"]="https://github.com/ros-controls/gazebo_ros2_control" ["gz_ros2_control"]="https://github.com/ros-controls/gz_ros2_control")
declare -A subrepo_pr=( ["ros2_control"]=$ROS2_CONTROL_PR ["ros2_controllers"]=$ROS2_CONTROLLERS_PR ["ros2_control_demos"]=$ROS2_CONTROL_DEMOS_PR ["gazebo_ros2_control"]=$GAZEBO_ROS2_CONTROL_PR ["gz_ros2_control"]=$GZ_ROS2_CONTROL_PR)
