name: "Install Dependencies"
on:
  workflow_call:

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --requirement requirements.txt
    - name: Install generate_parameter_library
      run: |
        cd
        git clone https://github.com/PickNikRobotics/generate_parameter_library.git
        cd generate_parameter_library/generate_parameter_library_py/
        python -m pip install .
