name: Iron Binary Build - main
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  workflow_dispatch:
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'

jobs:
  binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-target-workspace-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [iron]
        ROS_REPO: [main, testing]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: ${{ matrix.ROS_REPO }}
      target_workspace: ros_controls.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: master
