name: "Create Reviewer Stats"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
  # Run every morning to ensure component documentation is up to date on deployment
   - cron: '23 3 * * *'
  pull_request:

jobs:
  create-reviewer-stats:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --requirement requirements.txt
      shell: bash
    - name: Get stats
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python make_help_scripts/create_reviewer_stats.py
      shell: bash
    - name: Cache stats
      uses: actions/cache/save@v3
      with:
        key: reviewer-stats
        path: ~/reviews
