name: "Check Page for Warnings Humble"
on:
  workflow_dispatch:
  push:
    branches:
      - humble
  schedule:
  # Run every morning to ensure component documentation is up to date on deployment
   - cron: '23 5 * * *'

jobs:
  build-halt-on-warnings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: humble
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --requirement requirements.txt
      shell: bash
    - name: Install generate_parameter_library
      run: |
        cd
        git clone https://github.com/PickNikRobotics/generate_parameter_library.git
        cd generate_parameter_library/generate_parameter_library_py/
        python -m pip install .
      shell: bash
    - name: Build single version considering warnings as errors
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        make html-all-subrepos-with-errors
