name: "Check Page for Warnings (PR)"
on:
  workflow_dispatch:
  pull_request:

jobs:
  build-singleversion-halt-on-warnings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v6
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --requirement requirements.txt
      shell: bash
    - name: Install generate_parameter_library
      run: |
        cd
        git clone https://github.com/PickNikRobotics/generate_parameter_library.git
        cd generate_parameter_library/generate_parameter_library_py/
        python -m pip install .
      shell: bash
    - name: Install doxygen, graphviz, and LaTeX
      # Skip if PR not targeting default branch
      if: github.event.pull_request.base.ref == github.event.repository.default_branch
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz latexmk texlive-fonts-recommended texlive-latex-extra texlive-latex-recommended texlive-plain-generic texlive-xetex fonts-freefont-otf
    - name: Restore stats
      uses: actions/cache/restore@v5
      with:
        key: reviewer-stats-${{ github.run_id }}
        restore-keys: |
          reviewer-stats
        path: ~/reviews
    - name: Build single version considering warnings as errors
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        make html-all-subrepos-with-errors

    - name: Build Rolling PDF
      # Skip if PR not targeting default branch
      if: github.event.pull_request.base.ref == github.event.repository.default_branch
      run: make pdf-rolling

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      # Skip if PR not targeting default branch
      if: github.event.pull_request.base.ref == github.event.repository.default_branch
      with:
        name: html-artifacts-${{ github.event.pull_request.number }}
        path: _build/html
        retention-days: 30 # default 90
        compression-level: 9 # maximum compression, default 6
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

    - name: Find HTML artifacts link comment
      uses: peter-evans/find-comment@v4
      id: find-comment
      # Skip if PR from fork (https://github.com/peter-evans/create-or-update-comment/issues/444)
      # or not targeting default branch
      if: github.repository == github.event.pull_request.head.repo.full_name && github.event.pull_request.base.ref == github.event.repository.default_branch
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: "HTML artifacts:"

    - name: Create or update HTML artifacts link comment
      uses: peter-evans/create-or-update-comment@v4
      # Skip if PR from fork (https://github.com/peter-evans/create-or-update-comment/issues/444)
      # or not targeting default branch
      if: github.repository == github.event.pull_request.head.repo.full_name && github.event.pull_request.base.ref == github.event.repository.default_branch
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          HTML artifacts: ${{ steps.artifact-upload-step.outputs.artifact-url }}.

          To view the resulting site:
          1. Click on the above link to download the artifacts archive
          2. Extract it
          3. Open `html-artifacts-${{ github.event.pull_request.number }}/index.html` in your favorite browser
        edit-mode: replace
