name: "Check Page for Warnings"
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
  # Run every morning to ensure component documentation is up to date on deployment
   - cron: '23 5 * * *'
  pull_request: # only runs up through build of sphinx

jobs:
  install-deps:
    uses: ./.github/workflows/install-dependencies.yml

  build-halt-on-errors:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build multiversion considering warnings as errors
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        make multiversion-with-errors
