name: "Check Page for Broken Links"
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
  # Run every morning to ensure component documentation is up to date on deployment
   - cron: '23 5 * * *'
  pull_request: # only runs up through build of sphinx

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
    - name: Install doxygen and graphviz
      run: sudo apt-get install -y doxygen graphviz
    - name: Run linkchecker
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        make html-all-subrepos-with-api
        make linkcheck
