name: "Build Multiversion Page (PR)"
on:
  workflow_dispatch:
    inputs:
      BASE_BRANCH:
        description: 'Chose branch to run on'
        required: true
        default: 'master'
        type: choice
        options:
        - humble
        - iron
        - master
  pull_request:

jobs:
  build-multiversion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --requirement requirements.txt
      shell: bash
    - name: Install generate_parameter_library
      run: |
        cd
        git clone https://github.com/PickNikRobotics/generate_parameter_library.git
        cd generate_parameter_library/generate_parameter_library_py/
        python -m pip install .
      shell: bash
    - name: Install doxygen and graphviz
      run: sudo apt-get install -y doxygen graphviz
    - name: Build multiversion with API
      env:
        BASE_BRANCH: ${{ github.event.inputs.BASE_BRANCH }}
        BASE_BRANCH_PR: ${{ github.event.pull_request.head.ref }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        make multiversion-with-api
