name: "Check Page for Broken Links"
on:
  workflow_dispatch:
  push:
    branches:
      - iron
  schedule:
  # Run every morning to ensure component documentation is up to date on deployment
   - cron: '23 5 * * *'
  pull_request: # only runs up through build of sphinx

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --requirement requirements.txt
      shell: bash
    - name: Install generate_parameter_library
      run: |
        cd
        git clone https://github.com/PickNikRobotics/generate_parameter_library.git
        cd generate_parameter_library/generate_parameter_library_py/
        python -m pip install .
      shell: bash
    - name: Install doxygen and graphviz
      run: sudo apt-get install -y doxygen graphviz
    - name: Build page with API and run linkchecker
      run:  |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        make linkcheck-all-subrepos-with-api
